project_id = "wylpfknvuxpencrrgxyf"

[functions.remove-background]
verify_jwt = false

[functions.generate-attributes]
verify_jwt = false

[functions.generate-outfit]
verify_jwt = false

[functions.generate-outfits]
verify_jwt = false

[functions.get-outfits]
verify_jwt = false

[functions.record-outfit-view]
verify_jwt = false

[functions.migrate-images]
verify_jwt = false
